<?php

/**
 * @file
 * Contains ao_task55.module.
 */

function ao_task55_js_page_callback() {
    ctools_include('ajax');
    ctools_include('modal');

    $build['paragraph'] = [
        '#prefix' => '<p>',
        '#suffix' => '</p>',
        '#markup' => t('Click'),
    ];

    $text = t('Show a Popup');
    $dest = "";
    $alt = t('Show');

    $link = ctools_modal_text_button($text, $dest, $alt);

    $build['popup_link'] = [
        '$markup' => $link,
    ];

    return render($build);
}
  