<?php

/**
 * @file
 * Contains ao_task.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ao_task_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ao_task module.
    case 'help.page.ao_task':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
