<?php

/**
 * @file
 * Contains ao_task122_custom_event.module.
 */

use Drupal\ao_task122_custom_event\Event\PageLoadEvent;

/**
 * Implements hook_preprocess_HOOK().
 */
function ao_task122_preprocess_html(&$variables) {
  /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $dispatcher */
  $event_dispatcher = \Drupal::service('event_dispatcher');
  // Instantiate our event.
  $event = new PageLoadEvent($variables);
  // Get the event_dispatcher service and dispatch the event.
  $event_dispatcher->dispatch(PageLoadEvent::PREPROCESS_HTML, $event);
} 