<?php

use Drupal\node\Entity\Node;

/**
 * @file
 * Some hooks.
 */

/**
 * Implements hook_node_update().
 * After node update, this hook insert message in recent log.
 */

 // function ao_task118_recent_log_messages_node_insert(Drupal\Core\Entity\EntityInterface $entity) {
//     \Drupal::logger('ao_task118_recent_log_messages')->info("Node with title
//     %NODE_TITLE% of type %NODE_TYPE% has been updated");
// }

function ao_task118_recent_log_messages_node_update(Drupal\node\NodeInterface $node){
    \Drupal::logger('ao_task118_recent_log_messages')->info("Node with title" . " - " . $node->getTitle() . " - " . "of type" . " - " . $node->getType() . " - " . "has been updated");
}